--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Protect dropped Weapons
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 09.03.2024
	Last Edit  : 24.11.2025
	=====================================================================
--]]

xrs_facer_action_facer_execute = xrs_facer.action_facer.execute
xrs_facer.action_facer.execute = function(self)
    if get_mcm_config("protection_rule") ~= 1 then
        xrs_facer_action_facer_execute(self)
        return
    end

    local actor_drop_item = db.actor.drop_item
	db.actor.drop_item = function(_self, item)
        actor_drop_item(_self, item)
        protect_weapon(item:id())
    end

    xrs_facer_action_facer_execute(self)

    db.actor.drop_item = actor_drop_item
end

function protect_weapon(wep_id)
    se_save_var(wep_id, nil, "protected_from_npc_pickup", true)

    if get_mcm_config("protection_time") ~= 0 then
        CreateTimeEvent("protect_dropped_weapons", "remove_pickup_flag" .. wep_id, get_mcm_config("protection_time"), function(id)
            se_save_var(id, nil, "protected_from_npc_pickup", nil)
            return true
        end, wep_id)
    end
end

function actor_on_item_drop(item)
    local item_id = IsWeapon(item) and item:id()
    if item_id then
        protect_weapon(item_id)
    end
end

function npc_on_item_before_pickup(npc, item, flags)
    if item and se_load_var(item:id(), nil, "protected_from_npc_pickup") then
        flags.ret_value = false
    end
end

function actor_on_item_take(item)
    local item_id = item and item:id()
    if item_id and se_load_var(item_id, nil, "protected_from_npc_pickup") then
        se_save_var(item_id, nil, "protected_from_npc_pickup", nil)
    end
end

function on_option_change()
    if get_mcm_config("protection_rule") == 0 then
        RegisterScriptCallback("actor_on_item_drop", actor_on_item_drop)
    else
        UnregisterScriptCallback("actor_on_item_drop", actor_on_item_drop)
    end
end

function on_game_start()
    RegisterScriptCallback("npc_on_item_before_pickup", npc_on_item_before_pickup)
    RegisterScriptCallback("actor_on_item_take", actor_on_item_take)
    RegisterScriptCallback("on_option_change", on_option_change)
    on_option_change()
end

--===========================================================================
--
-- MCM
--
--===========================================================================

local cc = table.concat

local MCM_ROOT_ID = "tmmr"
local MCM_MODULE_ID = "protect_dropped_weapons"

defaults = {
    ["protection_rule"] = 1,
	["protection_time"] = 10
}

function get_mcm_config(key)
	local path = cc({ MCM_ROOT_ID, MCM_MODULE_ID, key }, "/")
	if ui_mcm then return ui_mcm.get(path) else return defaults[key] end
end

function on_mcm_load()
	return {
		id = MCM_MODULE_ID, sh = true, gr = {
			{ id = "title", type = "slide", link = "ui_options_slider_player", text = cc({ "ui_mcm", MCM_ROOT_ID, MCM_MODULE_ID, "title" }, "_"), size = { 512, 50 }, spacing = 20 },
            { id = "protection_rule", type = ui_mcm.kb_mod_radio, val = 2, def = defaults["protection_rule"],
				content = {
					{ 0, "tmmr_always_protect" },
					{ 1, "tmmr_protect_when_hit" }
				}
			},
			{ id = "protection_time", type = "track", val = 2, min = 0.0, max = 120.0, step = 0.5, def = defaults["protection_time"] }
		}
	}, MCM_ROOT_ID
end
