--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Protect dropped Weapons
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 09.03.2024
	Last Edit  : 09.04.2024
	=====================================================================
--]]

xrs_facer_action_facer_execute = xrs_facer.action_facer.execute
xrs_facer.action_facer.execute = function(self)
    xrs_facer_action_facer_execute(self)

    if get_mcm_config("protection_rule") ~= 1 then
        return
    end

    local target_id = load_var(self.object, "facer_target", nil)
	local target = target_id and db.storage[target_id] and db.storage[target_id].object
    if (not target) or (not self.end_time) then
		return
	end

    if self.hit_time ~= self.end_time then
        return
    end

    if target_id ~= AC_ID then
        return
    end

    local spos = utils_obj.safe_bone_pos(self.object, "bip01_neck")
    local tpos = utils_obj.safe_bone_pos(target, "bip01_neck")
    local ysub = spos.y - tpos.y

    if (ysub > 1.5) or (ysub <= -1.8) then
        return
    end

    if (spos:distance_to_xz(tpos) >= 3) or (self.object:animation_count() == 0) then
        return
    end

    -- Actor probably got punched and dropped his weapon

    local active_item = db.actor:active_item()
    if not active_item then
        return
    end

    temp_protect_weapon(active_item:id())
end

function temp_protect_weapon(wep_id)
    se_save_var(wep_id, nil, "protected_from_npc_pickup", true)

    if get_mcm_config("no_pickup_time") == 0 then
        return
    end

    CreateTimeEvent("protect_dropped_weapons", "remove_pickup_flag" .. wep_id, get_mcm_config("no_pickup_time"), function(id)
        se_save_var(id, nil, "protected_from_npc_pickup", nil)
        return true
    end, wep_id)
end

function actor_on_item_drop(item)
    if get_mcm_config("protection_rule") ~= 0 then
        return
    end

    local item_id = IsWeapon(item) and item:id()
    if item_id then
        temp_protect_weapon(item_id)
    end
end

function npc_on_item_before_pickup(npc, item, flags)
    if (not npc) or (not item) then
        return
    end

    if se_load_var(item:id(), nil, "protected_from_npc_pickup") then
        -- printf("Denying item %s for npc %s", item:section(), npc:name())
        flags.ret_value = false
    end
end

function on_game_start()
    RegisterScriptCallback("npc_on_item_before_pickup", npc_on_item_before_pickup)
    RegisterScriptCallback("actor_on_item_drop", actor_on_item_drop)
end

--===========================================================================
--
-- MCM
--
--===========================================================================

local cc = table.concat

local MCM_ROOT_ID = "tmmr"
local MCM_MODULE_ID = "protect_dropped_weapons"

defaults = {
    ["protection_rule"] = 1,
	["no_pickup_time"] = 10
}

function get_mcm_config(key)
	local path = cc({ MCM_ROOT_ID, MCM_MODULE_ID, key }, "/")
	if ui_mcm then return ui_mcm.get(path) else return defaults[key] end
end

function on_mcm_load()
	return {
		id = MCM_MODULE_ID, sh = true, gr = {
			{ id = "title", type = "slide", link = "ui_options_slider_player", text = cc({ "ui_mcm", MCM_ROOT_ID, MCM_MODULE_ID, "title" }, "_"), size = { 512, 50 }, spacing = 20 },
            { id = "protection_rule", type = ui_mcm.kb_mod_radio, val = 2, def = defaults["protection_rule"],
				content = {
					{ 0, "tmmr_always_protect" },
					{ 1, "tmmr_protect_when_hit" }
				}
			},
			{ id = "no_pickup_time", type = "track", val = 2, min = 0.0, max = 120.0, step = 0.5, def = defaults["no_pickup_time"] }
		}
	}, MCM_ROOT_ID
end
