--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Configurable Sleep Preconditions
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 10.01.2024
	Last Edit  : 27.02.2024
	=====================================================================
--]]

-- G.A.M.M.A. value
LAST_SLEEP_THRESHOLD = 5000

orig_ui_sleep_test_and_show = ui_sleep_dialog.UISleep.TestAndShow
ui_sleep_dialog.UISleep.TestAndShow = function(self, force)
	if get_mcm_config("immersive_sleep_patch") then
		local last_sleep = actor_status_sleep.get_last_sleep()
		if (last_sleep < LAST_SLEEP_THRESHOLD) and (not get_mcm_config("allow_awake")) then
			actor_menu.set_msg(1, game.translate_string("st_sleep_awake"), 4)
			disable_info("sleep_active")
			return
		end
	end
 
	if not force then
		local bleeding = db.actor.bleeding > 0
		local radiation = db.actor.radiation > 0
		
		-- Prevent sleep if bleeding and/or iradiated.
		if ((bleeding) and (not get_mcm_config("allow_bleeding"))) or ((radiation) and (not get_mcm_config("allow_radiation"))) then
			if ((bleeding) and (not get_mcm_config("allow_bleeding"))) and ((radiation) and (not get_mcm_config("allow_radiation"))) then
				actor_menu.set_msg(1, game.translate_string("st_sleep_bleeding_irradiated"), 5)
			elseif (bleeding) and (not get_mcm_config("allow_bleeding")) then
				actor_menu.set_msg(1, game.translate_string("st_sleep_bleeding"), 4)
			elseif (radiation) and (not get_mcm_config("allow_radiation")) then
				actor_menu.set_msg(1, game.translate_string("st_sleep_irradiated"), 4)
			end
			disable_info("sleep_active")
			return
		end
		
		-- Check if actor is inside a safe zone
		local actor_hide = GetEvent("current_safe_cover") and true or false
	
		-- Check if actor is inside a tent
		if not actor_hide then
			actor_hide = item_tent.get_nearby_tent(1.5)
		end	
		
		-- If all is no, dont sleep
		if (not actor_hide) and (not get_mcm_config("allow_unsafe")) then
			actor_menu.set_msg(1, game.translate_string("st_cant_sleep_find_shelter_mlr"), 4)
			disable_info("sleep_active")
			return
		end
	end
	
	self:Initialize()
	self:ShowDialog(true)
	Register_UI("UISleep", "ui_sleep_dialog")
end

--===========================================================================
--
-- MCM
--
--===========================================================================

local cc = table.concat

local MCM_ROOT_ID = "tmmr"
local MCM_MODULE_ID = "conf_sleep_conds"

defaults = {
	["allow_bleeding"] = false,
	["allow_radiation"] = false,
	["allow_unsafe"] = false,
	["allow_awake"] = false,
	["immersive_sleep_patch"] = false
}

function get_mcm_config(key)
	local path = cc({ MCM_ROOT_ID, MCM_MODULE_ID, key }, "/")
	if ui_mcm then return ui_mcm.get(path) else return defaults[key] end
end

function on_mcm_load()
	return {
		id = MCM_MODULE_ID, sh = true, gr = {
			{ id = "title", type = "slide", link = "ui_options_slider_night", text = cc({ "ui_mcm", MCM_ROOT_ID, MCM_MODULE_ID, "title" }, "_"), size = { 512, 50 }, spacing = 20 },
			{ id = "allow_bleeding", type = "check", val = 1, def = defaults["allow_bleeding"] },
			{ id = "allow_radiation", type = "check", val = 1, def = defaults["allow_radiation"] },
			{ id = "allow_unsafe", type = "check", val = 1, def = defaults["allow_unsafe"] },
			{ id = "allow_awake", type = "check", val = 1, def = defaults["allow_awake"] },
			{ id = "separator", type = "line" },
			{ id = "immersive_sleep_patch", type = "check", val = 1, def = defaults["immersive_sleep_patch"] }
		}
	}, MCM_ROOT_ID
end
