--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Disassembling Outfits gives Patches
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 26.01.2024
	Last Edit  : 26.01.2024
	=====================================================================
--]]

PATCH_CHANCE = 0.15

patch_to_give = nil

orig_item_parts_disassembly_outfit = item_parts.disassembly_outfit
item_parts.disassembly_outfit = function(obj, obj_d)
	if math.random() < PATCH_CHANCE then
		local outfit_comm = ini_sys:r_string_ex(obj:section(), "community")
		if (outfit_comm) and (outfit_comm ~= "") then
			local patch_section = gameplay_disguise.get_patch(outfit_comm, true)
			local is_unpatched = se_load_var(obj:id(), obj:name(), "unpatched")
			if (not is_unpatched) and (patch_section) then
				patch_to_give = patch_section
			end
		end
	end

	orig_item_parts_disassembly_outfit(obj, obj_d)
end

orig_item_parts_timer_disassembly_outfit = item_parts.timer_disassembly_outfit
item_parts.timer_disassembly_outfit = function(npc_id, result_details, result_conditions, name)
	-- Insert the patch into the disassembly parts list
	if patch_to_give then
		table.insert(result_details, patch_to_give)
		patch_to_give = nil
	end

	return orig_item_parts_timer_disassembly_outfit(npc_id, result_details, result_conditions, name)
end
