-- Monkey patch which ensures that locally rewarded stashes are really local

-- We always force local stashes
GetRandomStash = treasure_manager.get_random_stash
function treasure_manager.get_random_stash(no_spot, hint, spawn_local, inv_box)
        return GetRandomStash(no_spot, hint, true, inv_box)
end

-- Here we change the logic to find out which stashes are considered local
orig_treasure_manager_box_in_same_map = treasure_manager.box_in_same_map
function treasure_manager.box_in_same_map(id)
        if (not id) then return end
	local obj1, obj2 = alife():actor(), alife_object(id)

	return is_on_nearby_level(obj1, obj2)
end

function is_on_nearby_level(se_obj_1, se_obj_2)
	if not (se_obj_1 and se_obj_2) then return false end
        local obj1_level, obj2_level = get_obj_level(se_obj_1), get_obj_level(se_obj_2)

	if not (obj1_level and obj2_level) then
		return false
	end
	
	if (obj1_level == obj2_level)
                or level_directly_connected(obj1_level, obj2_level)
        then
		return true
        end
end

function get_obj_level(se_obj)
        if not se_obj then return end

	local sim = alife()
	local gg = game_graph()
	local level = sim:level_name(gg:vertex(se_obj.m_game_vertex_id):level_id())

        return level
end

-- Uses txr_routes.routes to determine, if those levels are 'neighbours'
function level_directly_connected(section_1, section_2)
        local routes = txr_routes.routes
        local map1, map2 = txr_routes.get_map(section_1), txr_routes.get_map(section_2)
        if not (map1 and map2) then return end

        for from, tbl in pairs(routes) do
                for to, restrictors in pairs(tbl) do
                        if not (from == map1 or from == map2) then goto continue end
                        if (from == map1 and to == map2)
                                or (from == map2 and to == map1)
                        then
                                -- printf("- %s and %s are directly connected!", map1, map2)
                                return true
                        end

                        :: continue ::
                end
        end
end
