--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Talk to Everyone
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Credits    : Vintar0
	Date       : 31.01.2024
	Last Edit  : 19.11.2025
	=====================================================================
--]]

xr_meet_process_npc_usability = xr_meet.process_npc_usability
xr_meet.process_npc_usability = function(npc)
	local meet = npc and db.storage[npc:id()].meet
	if meet then
		meet.meet_manager.use = "true"
	end

    xr_meet_process_npc_usability(npc)
end
