config = ini_file_ex("plugins\\rare_stash_links.ltx")

function is_on_nearby_level(se_obj_1, se_obj_2) -- linked and linked to linked level xddd
	if not (se_obj_1 and se_obj_2) then
		return false
	end
	
	local sim = alife()
	local gg = game_graph()
	
	local obj1_level = sim:level_name(gg:vertex(se_obj_1.m_game_vertex_id):level_id())
	local obj2_level = sim:level_name(gg:vertex(se_obj_2.m_game_vertex_id):level_id())

	if not (obj1_level and obj2_level) then
		return false
	end
	
	if (obj1_level == obj2_level) then
		return true
	end

	if string.find(config:r_value(obj1_level,"target_maps",0,""),obj2_level) then
		return true
	end
	
	return false
end

function treasure_manager.box_in_same_map(id)
	local obj1 = alife():actor()
	local obj2 = alife_object(id)
	return is_on_nearby_level(obj1, obj2)
end
