--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Task Marker for Delivery Tasks Fix
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 11.01.2024
	Last Edit  : 26.01.2024
	=====================================================================
--]]

orig_general_delivery = task_functor.general_delivery
task_functor.general_delivery = function(task_id, field, p, tsk)
	if (not db.actor) or (not tsk) then
		return nil
	end
	
	if field == "target" then
		local var = load_var(db.actor, task_id)
		if not var then
			return nil
		end
	
		if tsk.stage == 0 then
			-- If the player doesn't have the item in his inventory return the parent_id of the item
			local item_1_obj = var.item_1_id and alife_object(var.item_1_id)
			if (item_1_obj) and (item_1_obj.parent_id < 65535) then -- obj.parent_id >= 65535 -> obj on ground
				return item_1_obj.parent_id
			end

			return var.item_1_id
		end
		
		-- If quest item is found then return the package receiver id
		if tsk.stage == 1 then
			return var.target_id
		end
	end

	return nil
end

orig_drx_sl_quest_item_task_target = task_functor.drx_sl_quest_item_task_target
task_functor.drx_sl_quest_item_task_target = function(task_id, field, p, tsk)
	if (not db.actor) or (not tsk) then
		return nil
	end

	if field == "target" then
		local var = load_var(db.actor, task_id)
		if not var then
			return nil
		end

		-- Return the quest item location
		if tsk.stage == 0 then
			local se_obj = get_story_se_item("drx_sl_quest_item_" .. var.stash_type)
			if (se_obj) and (se_obj.parent_id < 65535) then -- obj.parent_id >= 65535 -> obj on ground
				return se_obj.parent_id
			end

			return se_obj.id
		end

		-- If quest item is found then return the quest giver id
		if tsk.stage == 1 then
			return tsk.task_giver_id
		end
	end

	return nil
end
