--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Mysteries of the Zone Unlocker
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Credits    : Hisalute
	Date       : 19.01.2024
	Last Edit  : 19.11.2025
	=====================================================================
--]]

function on_game_start()
	RegisterScriptCallback("on_specific_character_dialog_list", function(character_id, dialog_list)
		if character_id == "mar_smart_terrain_doc_doctor" then
			dialog_list:add("cit_doctor_main_dialog")
		end
	end)
end
