--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Drop from Inventory Hotkey
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 04.07.2025
	Last Edit  : 02.11.2025
	=====================================================================
--]]

local is_hotkey_pressed = false

ui_inventory_UIInventory_On_CC_Hover = ui_inventory.UIInventory.On_CC_Hover
ui_inventory.UIInventory.On_CC_Hover = function(self, bag, idx)
    ui_inventory_UIInventory_On_CC_Hover(self, bag, idx)

    if is_hotkey_pressed then
        local obj = self.CC[bag]:GetObj(idx)
	    if obj then
		    self:Action_Drop(obj, bag)
            is_hotkey_pressed = false
	    end
    end
end

function on_key_press(key)
    if key == get_mcm_config("key") then
		is_hotkey_pressed = true
	end
end

function on_key_hold(key)
    if key == get_mcm_config("key") and ui_mcm.key_hold("drop_from_inv_hotkey", key, 0) then
		is_hotkey_pressed = true
	end
end

function on_key_release(key)
    if key == get_mcm_config("key") then
		is_hotkey_pressed = false
	end
end

function on_game_start()
    RegisterScriptCallback("on_key_press", on_key_press)
	RegisterScriptCallback("on_key_hold", on_key_hold)
    RegisterScriptCallback("on_key_release", on_key_release)
end

--===========================================================================
--
-- MCM
--
--===========================================================================

local cc = table.concat

local MCM_ROOT_ID = "tmmr"
local MCM_MODULE_ID = "drop_from_inv_hotkey"

defaults = {
	["key"] = DIK_keys.DIK_LSHIFT
}

function get_mcm_config(key)
	local path = cc({ MCM_ROOT_ID, MCM_MODULE_ID, key }, "/")
	if ui_mcm then return ui_mcm.get(path) else return defaults[key] end
end

function on_mcm_load()
	return {
		id = MCM_MODULE_ID, sh = true, gr = {
			{ id = "title", type = "slide", link = "ui_options_slider_player", text = cc({ "ui_mcm", MCM_ROOT_ID, MCM_MODULE_ID, "title" }, "_"), size = { 512, 50 }, spacing = 20 },
			{ id = "key", type = "key_bind", val = 2, def = defaults["key"] }
		}
	}, MCM_ROOT_ID
end
