--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: NPC Wounded Animation Fix
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 11.01.2024
	Last Edit  : 19.01.2024
	=====================================================================
--]]

orig_action_wounded_initialize = xr_wounded.action_wounded.initialize
xr_wounded.action_wounded.initialize = function(self)
	orig_action_wounded_initialize(self)
	
	-- Make the NPC drop his weapon -> prevents the NPC from shoving his weapon away before entering the wounded animation
	local npc = self.object
	local item = npc:active_item()
	local slot = npc:active_slot()
	if (item) and ((slot == 2) or (slot == 3)) then
		npc:drop_item(item)
	end
end
