--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Dynamic News Heard Melee Fix
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 07.01.2024
	Last Edit  : 19.01.2024
	=====================================================================
--]]

orig_dnm_gossip_death_by_stalker = dynamic_news_manager.DynamicNewsManager.GossipDeathByStalker
dynamic_news_manager.DynamicNewsManager.GossipDeathByStalker = function(self, victim, who, comm) -- hearing stalker killing a stalker
	--printf(">>> Dyn News: GossipDeathByStalker - call")
	local cls = dynamic_news_helper.GetWeaponClass(who)
	-- Note: added cls == 6 (clsid.wpn_knife_s) here
	if (cls == 1 or cls == 6 or cls == 9) then 
		return false
	end
	
	if self:IsCommunitySame(victim,who) then
		return false
	end
	
	local sender = sender or self:FindSpeaker(victim,who,false,nil,true)
	if self:IsSpecialNPC(sender) then
		return false
	end
	
	local tbl_1 = utils_data.collect_translations("st_dyn_news_builder_hear_",true)
	local tbl_2 = utils_data.collect_translations("st_dyn_news_builder_ending_",true)
	if (not tbl_1) or (not tbl_2) then
		return false
	end
	
	local a = tbl_1[math.random(#tbl_1)]
	local b = dynamic_news_helper.GetWeaponDescription(who,2)
	local c = dynamic_news_helper.GetPointDescription(victim)
	local d = tbl_2[math.random(#tbl_2)]

	local Se = strformat("%s, %s",sender:character_name(),dynamic_news_helper.GetCommunityDescription(sender,6))
	local msg = strformat("%s %s %s. %s",a,b,c,d)
	
	self:PushToChannel(sender:character_community(),{Mg=msg,Ic=sender:character_icon(),Snd="news",Se=Se,It="npc"})
	
	return true
end

orig_dnm_gossip_death_of_mutant = dynamic_news_manager.DynamicNewsManager.GossipDeathOfMutant
dynamic_news_manager.DynamicNewsManager.GossipDeathOfMutant = function(self, victim, who, comm) -- hearing stalker killing a mutant
	--printf(">>> Dyn News: GossipDeathOfMutant - call")
	local cls = dynamic_news_helper.GetWeaponClass(who)
	-- Note: added cls == 6 (clsid.wpn_knife_s) here
	if (cls == 1 or cls == 6 or cls == 9) then 
		return false
	end
	
	local sender = self:FindSpeaker(victim,who,nil,false,true)
	if self:IsSpecialNPC(sender) then
		return false
	end
	
	local tbl_1 = utils_data.collect_translations("st_dyn_news_builder_hear_",true)
	local tbl_2 = utils_data.collect_translations("st_dyn_news_builder_ending_",true)
	if (not tbl_1) or (not tbl_2) then
		return false
	end
	
	local a = tbl_1[math.random(#tbl_1)]
	local b = dynamic_news_helper.GetWeaponDescription(who,2)
	local c = dynamic_news_helper.GetPointDescription(victim)
	local d = tbl_2[math.random(#tbl_2)]
	
	local Se = strformat("%s, %s",sender:character_name(),dynamic_news_helper.GetCommunityDescription(sender,6))
	local msg = strformat("%s %s %s. %s",a,b,c,d)
	
	self:PushToChannel(sender:character_community(),{Mg=msg,Ic=sender:character_icon(),Snd="news",Se=Se,It="npc"})
	
	return true
end
