--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: 500 Weight Slider
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 28.11.2023
	Last Edit  : 01.12.2025
	=====================================================================
--]]

NEW_WEIGHT = 500

ui_options_init_opt_base = ui_options.init_opt_base
ui_options.init_opt_base = function()
	ui_options_init_opt_base()

	local weight = follow_path(ui_options.options, { "gameplay", "gameplay_diff", "weight" })
	if not weight then
		return
	end

	weight.max = NEW_WEIGHT
end

ui_options.init_opt_base()

function find_child(list, id)
    if not list then
		return nil
	end

    for _, item in ipairs(list) do
        if item.id == id then
            return item
        end
    end

    return nil
end


function follow_path(root_list, ids)
	local current = nil
	local list = root_list

    for _, id in ipairs(ids) do
        current = find_child(list, id)
        if not current then
            printf("!500 Weight Slider: '%s' path is invalid", id)
            return nil
        end
        list = current.gr
    end

    return current
end
