--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: 500 Weight Slider
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 28.11.2023
	Last Edit  : 19.01.2024
	=====================================================================
--]]

NEW_WEIGHT = 500

orig_ui_options = ui_options.init_opt_base
ui_options.init_opt_base = function()
	orig_ui_options()

	if (ui_options.options[4].id ~= "gameplay") then
		printf("!500 Weight Slider: gameplay path is invalid")
		return
	end

	if (ui_options.options[4].gr[4].id ~= "gameplay_diff") then
		printf("!500 Weight Slider: gameplay_diff path is invalid")
		return
	end

	if (ui_options.options[4].gr[4].gr[8].id ~= "weight") then
		printf("!500 Weight Slider: weight path is invalid")
		return
	end

	ui_options.options[4].gr[4].gr[8].max = NEW_WEIGHT
end
ui_options.init_opt_base()
