--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Companion Wheel - Hold Fire Toggle
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Singustromo
	Date       : 21.09.2023
	Last Edit  : 01.02.2024
	=====================================================================
--]]

--[[
	Replaces the companion quick command for combat to be 'Ignore combat, but help me'
	(attack_only_actor_combat_enemy_state)
--]]

local parent = axr_companions

local combat_states = {
	"set_companion_to_attack_state",
	"set_companion_to_attack_only_actor_combat_enemy_state",
	"set_companion_to_ignore_combat_state"
}

function parent.cycle_companions_combat_mode(force_mode, no_msg)
	parent.cycle_state(combat_states, "combat", true, force_mode, no_msg )
end

function parent.set_companion_squad_combat_mode(mode,npc,squad)
	local f = this[combat_states[mode]]
	if (not f) then return end
	squad = squad or get_object_squad(npc)
	if not (squad and squad.commander_id) then return end
	if (axr_task_manager.hostages_by_id[squad:commander_id()]) then return end

	for k in squad:squad_members() do
		local member = db.storage[k.id] and db.storage[k.id].object
		if (member and member:alive()) then
			f(member)
		end
	end
end

-- Only possible with unlocalizer or by replacing the script all together
-- parent.cw_commands["combat"]    = {	key= "DIK_1"	,on_state= 1	,get= parent.get_companion_combat_mode		,set_one= parent.set_companion_squad_combat_mode	,set_all= parent.cycle_companions_combat_mode		,on_str= "st_set_companion_to_attack_state"					,off_str= "st_set_companion_to_attack_only_actor_combat_enemy_state"	}
