--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Re-enable Backpack Degradation
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 02.01.2025
	Last Edit  : 01.12.2025
	=====================================================================
--]]

function find_child(list, id)
    if not list then
		return nil
	end

    for _, item in ipairs(list) do
        if item.id == id then
            return item
        end
    end

    return nil
end


function follow_path(root_list, ids)
	local current = nil
	local list = root_list

    for _, id in ipairs(ids) do
        current = find_child(list, id)
        if not current then
            printf("!Re-enable Backpack Degradation: '%s' path is invalid", id)
            return nil
        end
        list = current.gr
    end

    return current
end

ui_options_init_opt_base = ui_options.init_opt_base
ui_options.init_opt_base = function()
	ui_options_init_opt_base()

	local economy_diff = follow_path(ui_options.options, { "gameplay", "economy_diff" })
	if not economy_diff then
		return
	end

	economy_diff.gr = economy_diff.gr or {}

	table.insert(economy_diff.gr, {
		id = "bkpk_degradation",
		type = "check",
		val = 1,
		curr = { ui_options.curr_economy, "bkpk_degradation" },
		functor = { ui_options.func_economy_diff, "bkpk_degradation" },
	})
end

ui_options.init_opt_base()
