--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Re-enable Backpack Degradation
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 02.01.2025
	Last Edit  : 02.01.2025
	=====================================================================
--]]

ui_options_init_opt_base = ui_options.init_opt_base
ui_options.init_opt_base = function()
	ui_options_init_opt_base()

	if (ui_options.options[4].id ~= "gameplay") then
		printf("!Re-enable Backpack Degradation: gameplay path is invalid")
		return
	end

	if (ui_options.options[4].gr[3].id ~= "economy_diff") then
		printf("!Re-enable Backpack Degradation: economy_diff path is invalid")
		return
	end

	table.insert(ui_options.options[4].gr[3].gr, {
		id = "bkpk_degradation",
		type = "check",
		val = 1,
		curr = { ui_options.curr_economy, "bkpk_degradation" },
		functor = { ui_options.func_economy_diff, "bkpk_degradation" },
	})
end

ui_options.init_opt_base()
